--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  annotations:
    kubernetes.io/change-cause: "updated to phpmyadmin"
spec: 
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1.23"
    spec: 
      containers:
        - name: nginx
          image: phpmyadmin
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              memory: "65Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"