---
apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  activeDeadlineSeconds: 10
  backoffLimit: 2
  template:
    metadata:
      name: jobpod
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpine
          image: alpine  
          command:
            - sleep
            - 10s