---
apiVersion: v1
kind: Pod
metadata:
  name: cm-literal-demo
spec:
  containers:
    - image: alpine
      name: alpine-cont
      args:
        - /bin/sh
        - -c
        - sleep 1d
      envFrom:
        - configMapRef:
            name: onevalue-cmap