--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: mysql-config 
spec: 
  containers:
    - image: mysql:8
      name: mysql
      envFrom: 
        - configMapRef: 
            name: mysql-configmap
            optional: false 
      ports:
        - containerPort: 3306
