--- 
apiVersion: v1
kind: Service
metadata: 
  name: dashboard
spec: 
  ports:
    - name: dashboard
      port: 80
      targetPort: 80
      protocol: TCP     
  selector:
    app: dashboard
  type: LoadBalancer


    

