--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
spec: 
  minReadySeconds: 1
  replicas: 8
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec: 
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              memory: "65Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"