--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: alpine-config-env 
spec: 
  containers:
    - image: alpine:1.23
      name: alpine
      envFrom: 
        - configMapRef:
            name: dummy-cm 
            optional: false 
// adding new line in config  
// adding second line 
//adding third line 