--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: alpine-config-env 
spec: 
  containers:
    - image: alpine
      name: alpine
      envFrom: 
        - configMapRef:
            name: dummy-cm 
            optional: false 
      args:
        - sleep
        - 1d 
