---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-demo
spec:
  containers:
    - image: alpine
      name: alpine-cont
      args:
        - /bin/sh
        - -c
        - sleep 1d
      volumeMounts:
        - name: secret-vol
          mountPath: "/secrets"
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: my-secret