--- 
apiVersion: v1 
kind: Pod
metadata:
  name: nodeselector
  labels:
    app: nginx
    purpose: nodeselector
spec:
  nodeSelector: 
    purpose: development 
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - containerPort:  8080
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
    resources:
      requests:
        memory: "65Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "1000m"