--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: alpine-pvtregistry
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template: 
    metadata:
      name: alpine-pod
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: 736644755789.dkr.ecr.eu-north-1.amazonaws.com/vcdevops:latest
            - sleep
            - 1d 
      imagePullSecrets:
        - name: docker-cfg
 