---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-mysql-disk
spec: 
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-premium
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - name: mysql
          containerPort: 3306
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-volume
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: qtdevops
        - name: MYSQL_DATABASE
          value: qtecommerce
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: azure-mysql-disk
