---
apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
spec:
  containers:
    - image: alpine
      name: alpine-cont
      args:
        - /bin/sh
        - -c
        - sleep 1d
  nodeSelector:
    disktype: ssd