---
apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod1
spec:
  containers:
    - image: alpine
      name: alpine-cont
      args:
        - /bin/sh
        - -c
        - sleep 1d
  tolerations:
    - key: "special"
      operator: "Equal"
      value: "true"
      effect: NoSchedule