---
apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod2
spec:
  containers:
    - image: alpine
      name: alpine-cont
      args:
        - /bin/sh
        - -c
        - sleep 1d
  tolerations:
    - key: "special"
      operator: "Exists"
      effect: NoSchedule