#restart OnFailure
--- 
apiVersion: v1
kind: Pod
metadata:
  name: restartonfailure
spec:
  restartPolicy: OnFailure
  containers:
    - name: failure  
      image: alpine
      args:
        - sleep
        - 3SM

--- 
apiVersion: v1
kind: Pod
metadata:
  name: restartonfailure2
spec:
  restartPolicy: OnFailure
  containers:
    - name: sucess 
      image: alpine
      args:
        - sleep
        - 3s