--- 
apiVersion: v1
kind: Service
metadata: 
  name: nginx--lb
spec: 
  ports:
    - name: nginx--lb    
      port: 80
      targetPort: 80
      protocol: TCP     
  selector:
    app: nginx
  type: LoadBalancer

