---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hostdir
spec:
  containers:
    - image: alpine
      name: alpine
      args:
        - /bin/sh
        - -c
        - sleep 1d
      volumeMounts:
        - mountPath: /var/log
          name: logs-volume
  volumes:
    - name: logs-volume
      hostPath:
        path: /var/log
        type: Directory
