--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkinsdeployment
spec:
  minReadySeconds: 5
  replicas: 8
  selector:
    matchLabels:
      app: jenkins
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 50%
        maxUnavailable: 50%
    template:
      metadata:
        name: jenkins
      spec: 
        containers:
          - image: jenkins/jenkins:lts-jdk11
            name:  jenkins
            ports:
              - containerPort: 8080 